- name: "Purge existing Prod image {{ new_template_id }}"
  shell: |
    # Bruteforce cleanup of config and disks if they exist
    rm -f /etc/pve/qemu-server/{{ new_template_id }}.conf
    qm destroy {{ new_template_id }} --purge || true
  delegate_to: "{{ pve_node }}"
  failed_when: false

- name: "Clone Dev to Prod ID"
  shell: >
    /usr/sbin/qm clone {{ vmid_to_clone }} {{ new_template_id }} 
    --full --name {{ prod_host }} 
    --storage {{ golden_storage }}
  delegate_to: "{{ pve_node }}"
  become: true


    