- name: Deploy settings.php and Apache Vhost
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: www-data
    group: www-data
  loop:
    - { src: "{{ drupal_template_dir }}/settings.php.j2", dest: "/var/www/html/sites/default/settings.php" }
    - { src: "{{ drupal_template_dir }}/haproxy-target.conf.j2", dest: "/etc/apache2/sites-available/haproxy-target.conf" }
  become: true

- name: Enable Site in Apache
  ansible.builtin.command: a2ensite haproxy-target
  register: ensite_result
  changed_when: "'Enabling site' in ensite_result.stdout"
  become: true

- name: Ensure default Apache site is disabled
  ansible.builtin.command: a2dissite 000-default.conf
  become: true

- name: Restart Apache
  ansible.builtin.service:
    name: apache2
    state: restarted
  become: true