packer {
  required_plugins {
    proxmox = {
      version = ">= 1.1.2"
      source  = "github.com/hashicorp/proxmox"
    }
    ansible = {
      version = ">= 1.1.0"
      source  = "github.com/hashicorp/ansible"
    }
  }
}

locals {
  my_public_key = trimspace(file("~/.ssh/id_rsa.pub"))
}

variable "ssh_password" {
  type      = string
  sensitive = true
  default   = null 
}

variable "proxmox_vmid" {
  type        = string
  description = "The specific VMID from NetBox inventory. Generated by script"
}

variable "proxmox_api_token_secret" {
  type      = string
  sensitive = true
}

variable "target_app" {
  type    = string
  # No default, must be an argument
}

variable "proxmox_api_url" { type = string }

variable "clone_template_name" {
  type    = string
  default = "debian-trixie-golden" 
}

source "proxmox-clone" "drupal-base" {
  proxmox_url = var.proxmox_api_url
  vm_id       = var.proxmox_vmid
  username    = "terraform@pam!main_terraform"
  token       = var.proxmox_api_token_secret

  node    = "pve"

  # Template source settings
  clone_vm = var.clone_template_name
  full_clone = true

  # Enable QEMU agent so Packer can query the IP
  qemu_agent = true

  # Instruct Proxmox Cloud-Init to assign DHCP on boot
  ip_config {
    ip = "dhcp"
  }

  # Target VM settings
  vm_name = "${var.target_app}-dev-golden"
  pool     = "Template"

  cores  = 4
  memory = 4096

  ssh_username = "kevin"
  ssh_handshake_attempts = 100
  ssh_timeout  = "15m"
  ssh_private_key_file = "~/.ssh/id_rsa"
}

build {
  sources = ["source.proxmox-clone.drupal-base"]

  # Step 1: Run your existing Ansible roles
  provisioner "ansible" {
    playbook_file = "./playbooks/_packer-build.yaml"
    user          = "kevin"
    use_proxy     = false
    ansible_env_vars = [
      "ANSIBLE_ROLES_PATH=./roles",
      "ANSIBLE_HOST_KEY_CHECKING=False"
    ]
    # Pass target_app variable
    extra_arguments = [
      "--extra-vars", "target_app=${var.target_app}"
    ]
  }

  # Step 2: Final Sanitization 
  provisioner "shell" {
    inline = [
      "sudo swapoff -a",
      "sudo sed -i '/swap/d' /etc/fstab",
      "echo 'y' | sudo parted /dev/sda rm 5 || true",
      "echo 'y' | sudo parted /dev/sda rm 2 || true",
      "sudo cloud-init clean --logs",
      "sudo truncate -s 0 /etc/machine-id",
      "sudo cloud-init clean --logs", # Crucial: Tells the OS "You haven't booted yet"
      "sudo rm -f /etc/netplan/*", # Remove Packer's network config
      "sudo truncate -s 0 /etc/machine-id",
      "sudo sync",
      "sudo rm /etc/environment"
    ]
  }
  post-processor "shell-local" {
    inline = [
      # copy the disk from local-zfs to NAS (nfs)
    "ssh root@pve 'qm move_disk ${var.proxmox_vmid} scsi0 truenas-nfs --delete'"    ]
  }
}