php_packages:
  - php
  - php-gd
  - php-mysql
  - php-xml
  - php-mbstring
  - php-curl

system_packages:
  - apache2
  - default-mysql-client
  - ncdu
  - vim
  - nfs-common
  - htop
  - qemu-guest-agent
  - ceph-common
  