- name: Force Terraform to recreate node
  delegate_to: terraform
  shell: |
    terraform apply \
      -replace='proxmox_vm_qemu.proxmox_vms["{{ inventory_hostname }}"]' \
      -auto-approve
  args:
    chdir: "/home/kevin/terraform"
  throttle: 1
  async: 600       
  poll: 10         
  vars:
    ansible_command_timeout: 600
    ansible_connect_timeout: 600
