- name: Force Terraform to recreate node
  delegate_to: terraform
  shell: |
    terraform apply \
      -replace='proxmox_vm_qemu.proxmox_vms["{{ inventory_hostname }}"]' \
      -auto-approve
  args:
    chdir: "/home/kevin/terraform"
  throttle: 1
  async: 600       # Allow the task to run for up to 10 minutes
  poll: 10         # Check back every 10 seconds for status
  vars:
    ansible_command_timeout: 600
    ansible_connect_timeout: 600