- name: Serial Rolling Deploy for Dev
  hosts: "repo_{{ target_app | default('UNDEFINED') }}:&env_dev"
  serial: 1  
  roles:
    - role: terraform_refresh

- name: Database operations
  hosts: "repo_{{ target_app | default('UNDEFINED') }}:&env_dev"
  roles:
    - role: drupal_db_ops