- name: Serial Rolling Deploy for Prod
  hosts: "repo_{{ target_app | default('UNDEFINED') }}:&env_prod"
  serial: 1  
  roles:
    - role: terraform_refresh

- name: Database operations
  hosts: "repo_{{ target_app | default('UNDEFINED') }}:&env_prod"
  roles:
    - role: drupal_db_ops