- name: Setup templated Drupal install for packer image
  hosts: all
  vars_files:
    - /home/kevin/db-server/playbook/vault.yaml
    - /home/kevin/drupal/group_vars/vault.yaml
    - /home/kevin/drupal/group_vars/all.yaml
  become: true
  vars:
    - target_app: nerdperk
  roles:
    - drupal_dependencies
    - drupal_deploy