- name: Setup templated Drupal install for packer image
  hosts: all
  become: true
  roles:
    - drupal_dependencies
    - drupal_composer
    # Do NOT include drupal_db_ops here if it targets a specific DB server
    # Do NOT include drupal_storage if it mounts environment-specific NFS