- name: Setup templated Drupal install for packer image
  hosts: all
  vars_files:
    - /home/kevin/db-server/playbook/vault.yaml
    - /home/kevin/drupal/group_vars/vault.yaml
    - /home/kevin/drupal/group_vars/all.yaml
  become: true
  vars:
    - target_app: nerdperk
  roles:
    - drupal_dependencies
    - drupal_deploy
    # Do NOT include drupal_db_ops here if it targets a specific DB server
    # Do NOT include drupal_storage if it mounts environment-specific NFS