- name: "DEBUG: Show resolved hostnames and available variables"
  debug:
    msg: 
      - "Target App: {{ target_app }}"
      - "Resolved Dev Host: {{ dev_host }}"
      - "Resolved Prod Host: {{ prod_host }}"

# - name: "Promote {{ target_app }} from Dev to Prod"
#   hosts: localhost
#   gather_facts: false
#   vars:
#     # Resolve Dev/Prod host identities from inventory intersections
#     dev_host: "{{ (groups['repo_' ~ target_app] | intersect(groups['env_dev']) | intersect(groups['role_vm_template']))[0] }}"
#     prod_host: "{{ (groups['repo_' ~ target_app] | intersect(groups['env_prod']) | intersect(groups['role_vm_template']))[0] }}"
    
#     # Map vars for readability in shell commands
#     vmid_to_clone: "{{ hostvars[dev_host].vmid }}"
#     new_template_id: "{{ hostvars[prod_host].vmid }}"
#     pve_node: "pve"
#     golden_storage: "truenas-nfs"

#   roles:
#     - proxmox_promote