- name: Update the theme
  hosts: "repo_{{ target_app | default('UNDEFINED') }}:&env_prod:&role_drupal"
  roles:
    - drupal_theme
    - drupal_settings

- name: Database operations for prod
  run_once: true
  hosts: "repo_{{ target_app | default('UNDEFINED') }}:&env_prod:&role_drupal"
  vars: 
    - env: "prod"
  roles:
    - drupal_db_ops