- name: Update the theme
  hosts: "repo_{{ target_app | default('UNDEFINED') }}:&env_dev:&role_drupal"
  vars_files:
    - /home/kevin/db-server/playbooks/vault.yaml
  roles:
    - drupal_theme
    - drupal_configure

- name: Database operations for dev
  run_once: true
  hosts: "repo_{{ target_app | default('UNDEFINED') }}:&env_dev:&role_drupal"
  vars: 
    - env: "dev"
  roles:
    - drupal_db_ops